---
#
# Ansible managed
#
repository:
  description: Install and configure Nomad.
  homepage: https://buluma.github.io/
  topics: hashicorp, nomad, server, agent, cluster, ansible, molecule, playbook
